// app_unity.cpp — Single compilation unit for the entire src/app/ tree.
//
// Every .cpp in the project is #included exactly once here.
// Headers use #pragma once — do NOT add include guards here.
//
// MOC output (#include "gen/moc_*.cpp") goes at the bottom, after all
// implementation files, so the Q_OBJECT machinery sees the full class
// definitions before the generated code tries to use them.
//
// Build script discipline (from design_cpp.md §9):
//   - Adding a new .cpp that uses Q_OBJECT requires:
//       1. An #include line below in the "Implementation" section.
//       2. A moc invocation in build_win32.bat / build_macos.sh.
//       3. A corresponding gen/moc_<ClassName>.cpp include in the MOC section.
//   - If you forget step 2/3 you get a clear linker error (undefined vtable),
//     not silent misbehaviour.
//
// This file intentionally has NO #pragma once — it is a build root, not a
// reusable header.

// ---- Implementation files -------------------------------------------------

#include "main.cpp"
#include "StateManager.cpp"
#include "MainWindow.cpp"

// Tabs (not yet implemented — add #includes here as files are created)
// #include "tabs/CamerasTab.cpp"
// #include "tabs/IntrinsicTab.cpp"
// #include "tabs/ExtrinsicTab.cpp"
// #include "tabs/ProcessTab.cpp"
// #include "tabs/WorkoutPage.cpp"

// Widgets (not yet implemented)
// #include "widgets/CameraGrid.cpp"
// #include "widgets/SkeletonView.cpp"
// #include "widgets/VideoPlayer.cpp"
// #include "widgets/ProgressGraph.cpp"

// Workers (not yet implemented)
// #include "workers/CameraWorkers.cpp"
// #include "workers/CalibrationWorkers.cpp"
// #include "workers/OfflineWorker.cpp"

// Analysis bridge (not yet implemented)
// #include "analysis/AnalysisBridge.cpp"

// ---- MOC output (generated by build script Step 1) ------------------------
// These are generated files — do not edit them manually.
// The build script runs moc on every .h file in src/app/ and its
// subdirectories, writing output to gen/moc_<ClassName>.cpp.

#include "gen/moc_StateManager.cpp"
#include "gen/moc_MainWindow.cpp"
